#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=70

start() {
	mkdir -m 0755 -p /var/cache/cups
	mkdir -m 0755 -p /var/cups
	mkdir -m 0755 -p /var/spool/cups/tmp
	service_start /usr/sbin/cupsd
}

stop() {
	service_stop /usr/sbin/cupsd
	sleep 1
	kill $(pidof cupsd) >/dev/null 2>&1 || killall -9 cupsd >/dev/null 2>&1
}

reload() {
	stop
	sleep 1
	start
	echo "cupsd daemon restarted."
}
